# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import datetime # agregado 16nov2021
sys.path.insert(0, os.path.abspath("../.."))
import solarwindpy

# -- Project information -----------------------------------------------------

project = 'solarwindpy'
copyright = '2021, Adriana Gulisano, Adel Arja, Violeta Bazzano, Agustin Velazquez, Ricardo Pafundi'
author = 'Adriana Gulisano, Adel Arja, Violeta Bazzano, Agustin Velazquez, Ricardo Pafundi'

# The full version, including alpha/beta/rc tags
release = solarwindpy.__version__


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.mathjax',#agregado 16nov2021
              'sphinx.ext.napoleon', #agregado 16nov2021
              'sphinx.ext.coverage', #agregado 16nov2021
              'sphinx.ext.doctest'] #agregado 16nov2021

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filename
# you can specify multiple suffix as o list of string:
# source_suffix = ['.rst,'.md']
source_suffix = '.rst'

# The master toctree document

master_doc = 'index'

# To use cross references, that is, numering of tables, figures, codes
# and equations if they have an object footer, and be referenced in the
# text by the number

numfig = True
numfig_format = {'figure': 'Fig.%s', 'table': 'Tabla %s', 'code-block': 'Codigo %s', 'section': 'Seccion %s'}
numfig_secnum_depth = 1
math_numfig = True
math_eqref_format = 'Ec. {number}'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Output file base name for HTML help builder

htmlhelp_basename = 'solarwindpy doc'

# -- Options for LaTex output

latex_elements = {
    'preamble': '''
    \\hypersetup{unicode=true}
    \\usepackage{CJKutf8}
    \\AtBeginDocument{\\begin{CKJ}{UTF8}{gbsn}}
    \\AtEndDocument{\\end{CJK}}
    ''',
}


# Grouping the document tree into LaTex files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class])

latex_documents = [
    (master_doc, 'Solarwindpy Manual.tex', 'SOLARWINDPY Documentation',
     'Adriana Gulisano, Adel Arja, Violeta Bazzano, Agustin Velazquez, Ricardo Pafundi', 'manual'),
]

    #One entry per manual page. List of tuples
    # (source start files, name, description, authors, manual section),
man_pages = [
        (master_doc, 'SOLARWINDPY', 'SOLARWINDPY',
        [author], 1)
]

# Grouping the document tree into Texinfo files, list of tuples
# (source start file, target name, title, author,
# dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'SOLARWINDPY', 'SOLARWINDPY',
    author, 'SOLARWINDPY', 'One line description of project.',
    'Miscellaneous'),
]

# If true, 'todo' and 'todoList' produce otuput, else they prodce nothing
todo_include_todos = True